"use client";

import { motion } from "framer-motion";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef, type ComponentType } from "react";
import {
  IconArrowRight,
  IconBrain,
  IconChecklist,
  IconFileAnalytics,
  IconMessageChatbot,
  IconReportAnalytics,
  IconSparkles,
  IconUsers,
} from "@tabler/icons-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { AgentChatSurface } from "@/features/recruitment/components/chat/agent-chat-surface";
import { useStatisticsChatController } from "@/features/recruitment/components/chat/use-statistics-chat-controller";
import type { UserRole } from "@/features/recruitment/types";
import { cn } from "@/lib/utils";

interface AgentWorkspaceClientProps {
  role: UserRole;
  userName: string;
}

interface AgentWorkflow {
  title: string;
  description: string;
  prompt: string;
  icon: ComponentType<{ className?: string }>;
}

const ROLE_LABELS: Record<UserRole, string> = {
  ta: "Talent Acquisition",
  manager: "Manager",
  hr: "Human Resources",
  admin: "Administrator",
};

const WORKFLOWS: AgentWorkflow[] = [
  {
    title: "Pipeline diagnosis",
    description: "Find bottlenecks, stalled stages, and next actions.",
    prompt:
      "Analyze the current recruitment pipeline. Highlight bottlenecks, stalled candidates, and the highest-impact next actions for my role.",
    icon: IconReportAnalytics,
  },
  {
    title: "CV matching room",
    description: "Rank profiles against the latest open job with reasons.",
    prompt:
      "Match the strongest CVs to the latest open job. Explain the ranking, gaps, and recommended screening focus for each candidate.",
    icon: IconUsers,
  },
  {
    title: "Interview kit",
    description: "Generate role-aware questions and evaluation criteria.",
    prompt:
      "Generate a structured interview kit for the next candidate in my queue, including competencies, questions, red flags, and scorecard guidance.",
    icon: IconChecklist,
  },
  {
    title: "Job requirement review",
    description: "Tighten vague requirements before publishing or matching.",
    prompt:
      "Review the most recent job requirement. Identify ambiguous criteria, missing skills, biased wording, and improvements for better CV matching.",
    icon: IconFileAnalytics,
  },
];

const CAPABILITIES = [
  "Conversation history is persistent across pages.",
  "Tool traces stay visible for auditability.",
  "Files generated by the agent appear inside the chat.",
  "The floating assistant remains for quick contextual questions.",
];

export function AgentWorkspaceClient({
  role,
  userName,
}: AgentWorkspaceClientProps) {
  const chat = useStatisticsChatController({ enabled: true });
  const searchParams = useSearchParams();
  const appliedPromptRef = useRef<string | null>(null);
  const prompt = searchParams.get("prompt")?.trim();
  const roleLabel = ROLE_LABELS[role] ?? ROLE_LABELS.ta;

  useEffect(() => {
    if (!prompt || appliedPromptRef.current === prompt) return;
    appliedPromptRef.current = prompt;
    chat.setInput(prompt);
  }, [chat, prompt]);

  return (
    <div className="relative isolate flex min-h-[calc(100vh-7rem)] flex-col gap-6 overflow-hidden rounded-[2rem] border border-border/60 bg-mesh p-5 shadow-sm md:p-8">
      <div className="pointer-events-none absolute right-[-10%] top-[-20%] -z-10 size-96 rounded-full bg-primary/15 blur-3xl" />
      <div className="pointer-events-none absolute bottom-[-20%] left-[10%] -z-10 size-80 rounded-full bg-chart-2/10 blur-3xl" />

      <motion.div
        initial={{ opacity: 0, y: -12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
        className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"
      >
        <div className="flex max-w-3xl flex-col gap-4">
          <div className="flex flex-wrap items-center gap-2">
            <Badge variant="secondary" className="w-fit gap-1.5 rounded-full px-3 py-1">
              <IconSparkles className="size-3.5" />
              Hybrid AI workspace
            </Badge>
            <Badge variant="outline" className="w-fit rounded-full px-3 py-1">
              {roleLabel} context
            </Badge>
          </div>
          <div className="flex flex-col gap-3">
            <h1 className="max-w-4xl text-4xl font-extrabold tracking-tight md:text-6xl">
              Intelligence Agent
            </h1>
            <p className="max-w-2xl text-base leading-7 text-muted-foreground md:text-lg">
              A full-screen workspace for analysis that is too important for a
              small chat window: CV matching, pipeline reasoning, interview
              kits, generated reports, and traceable recommendations.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-border/60 bg-card/70 p-3 backdrop-blur">
          <div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
            <IconBrain className="size-5" />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-semibold leading-none">{userName}</p>
            <p className="mt-1 text-xs text-muted-foreground">
              Workspace bound to your authenticated role
            </p>
          </div>
        </div>
      </motion.div>

      <div className="grid min-h-[720px] gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.55, delay: 0.1, ease: [0.22, 1, 0.36, 1] }}
          className="min-h-0 overflow-hidden rounded-[1.5rem] border border-border/70 bg-card/85 shadow-2xl shadow-primary/5 backdrop-blur-xl"
        >
          <AgentChatSurface
            controller={chat}
            variant="workspace"
            contextLabel={`${roleLabel} workspace`}
          />
        </motion.div>

        <motion.aside
          initial={{ opacity: 0, x: 16 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.55, delay: 0.18, ease: [0.22, 1, 0.36, 1] }}
          className="flex min-h-0 flex-col gap-4"
        >
          <Card className="border-border/70 bg-card/80 backdrop-blur-xl">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-base">
                <IconMessageChatbot className="size-4 text-primary" />
                When to use this page
              </CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col gap-3 text-sm text-muted-foreground">
              {CAPABILITIES.map((capability) => (
                <div key={capability} className="flex gap-2 leading-6">
                  <span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" />
                  <span>{capability}</span>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="flex-1 border-border/70 bg-card/80 backdrop-blur-xl">
            <CardHeader>
              <CardTitle className="text-base">Start a workflow</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col gap-3">
              {WORKFLOWS.map((workflow) => {
                const Icon = workflow.icon;
                return (
                  <button
                    key={workflow.title}
                    type="button"
                    disabled={chat.isStreaming}
                    onClick={() => void chat.sendMessage(workflow.prompt)}
                    className={cn(
                      "group flex w-full items-start gap-3 rounded-2xl border border-border/70 bg-background/50 p-4 text-left transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/35 hover:bg-background disabled:pointer-events-none disabled:opacity-60",
                    )}
                  >
                    <span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground">
                      <Icon className="size-4" />
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="block text-sm font-semibold text-foreground">
                        {workflow.title}
                      </span>
                      <span className="mt-1 block text-xs leading-5 text-muted-foreground">
                        {workflow.description}
                      </span>
                    </span>
                    <IconArrowRight className="mt-1 size-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-primary" />
                  </button>
                );
              })}
            </CardContent>
          </Card>

          <Separator />

          <div className="rounded-2xl border border-dashed border-border/80 bg-background/35 p-4 text-xs leading-5 text-muted-foreground">
            Keep the floating assistant for quick page-aware questions. Use this
            workspace when the answer needs room for tables, reports, downloads,
            or a defensible reasoning trail.
          </div>
        </motion.aside>
      </div>
    </div>
  );
}
